version: '2'
volumes:
  web_assets:
    driver: local

services:
  app:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    links:
      - database:db
    volumes:
      - web_assets:/app/public/
    env_file: development.env

  database:
    image: postgres:9.5
    environment:
      POSTGRES_USER: ttrack
      POSTGRES_PASSWORD: ttrack

  assetCompiler:
    build:
      context: ../
      dockerfile: docker/Dockerfile.builder
    command: node_modules/.bin/webpack --watch
    volumes:
      - web_assets:/app/public/
      - ../src/client/:/app/src/client
      - ../src/common/:/app/src/common
